name: kaist-village-hall-prod

services:
  api:
    image: yuwol/kaist-village-hall-api
    container_name: kaist-village-hall-prod-api
    env_file: .env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:16.3
    container_name: kaist-village-hall-prod-db
    ports:
      - '${DB_PORT:?err}:5432'
    environment:
      - POSTGRES_USER=${DB_USER:?err}
      - POSTGRES_PASSWORD=${DB_PASSWORD:?err}
      - POSTGRES_DB=${DB_NAME:?err}
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
